#!/bin/bash
set -e

COUNT=${1:-1000}

# Generate BenchmarkData.cs:
#   - COUNT simple entity classes (no test/Moq/EF dependencies)
#   - BenchmarkData.Queries: one typed lambda per entity type
#
# Each lambda: List<EntityN>.AsQueryable().Where(e=>e.Id>=t).OrderBy(e=>e.Name).Count()
#   Called at runtime → AsQueryable() creates fresh EnumerableQuery each call
#   → new ConstantExpression → new EnumerableExecutor<int> → Expression.Compile()
#   → JIT compiles DynamicMethod → GenericsHelpers.ClassWithSlotAndModule lock

BENCH="BenchmarkData.cs"
cat > "$BENCH" << 'HEADER'
// Auto-generated by generate.sh — do not edit.
// Entity types and pre-built benchmark lambdas for BenchmarkProgram.cs.
namespace Repro;

HEADER

for i in $(seq 1 $COUNT); do
cat >> "$BENCH" << EOF
public class BenchEntity${i} { public int Id { get; set; } public string Name { get; set; } = ""; public bool IsActive { get; set; } }
EOF
done

cat >> "$BENCH" << 'CLASSHEADER'

public static class BenchmarkData
{
    // Static per-type data, populated once at startup.
    // AsQueryable() is called inside each lambda (not here) so every
    // Execute() call gets a fresh EnumerableQuery → fresh expression tree.
CLASSHEADER

for i in $(seq 1 $COUNT); do
echo "    static readonly System.Collections.Generic.List<BenchEntity${i}> _d${i} = new() { new(){Id=$((i)),Name=\"a\",IsActive=true}, new(){Id=$((i+1)),Name=\"b\"}, new(){Id=$((i+2)),Name=\"c\",IsActive=true}, new(){Id=$((i+3)),Name=\"d\"}, new(){Id=$((i+4)),Name=\"e\",IsActive=true} };" >> "$BENCH"
done

cat >> "$BENCH" << 'ARRAYHDR'

    // One lambda per entity type; called in parallel — triggers parallel Expression.Compile().
    public static readonly System.Func<int, int>[] Queries = {
ARRAYHDR

for i in $(seq 1 $COUNT); do
printf "        threshold => _d%d.AsQueryable().Where(e => e.Id >= threshold).OrderBy(e => e.Name).Count(),\n" $i >> "$BENCH"
done

cat >> "$BENCH" << 'FOOTER'
    };
}
FOOTER

echo "Generated BenchmarkData.cs ($COUNT entity types)"
